# Uncomment the next line to define a global platform for your project
platform :osx, '10.11'

target 'PhantomX' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Starscream'
  pod 'CocoaAsyncSocket'
  pod 'Canary/Swift'
#  pod 'Swifter'

  # Pods for PhantomX

  target 'PhantomXTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
