# Uncomment the next line to define a global platform for your project
platform :osx, '10.12'

if File.exists?('Podfile.lock')
  puts "\033[33mPodfile.lock removed\033[0m"
  `rm Podfile.lock`
end

install! 'cocoapods',
  :generate_multiple_pod_projects => true,
  :incremental_installation => true

target 'PhantomX' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Starscream'
  pod 'CocoaAsyncSocket'
  pod 'CocoaLumberjack/Swift'
  pod 'CryptoSwift'
  pod 'Preferences'
  pod 'SwiftyJSON'
  pod 'SwifterSwift'

  # Pods for PhantomX

  target 'PhantomXTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
  end

end
