# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'phantom' do
  pod 'Starscream'
  
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for phantom

  target 'phantomTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
